CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP DEFAULT NOW(),
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(500) NOT NULL
);