CREATE TABLE IF NOT EXISTS withdrawals (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(19) NOT NULL,
    user_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
    processed_at TIMESTAMP DEFAULT NOW(),
    sum NUMERIC NOT NULL DEFAULT 0,
    UNIQUE(user_id, order_number)
);