CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    number VARCHAR(19) UNIQUE NOT NULL,
    user_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
    status VARCHAR(10) NOT NULL,
    uploaded_at TIMESTAMP DEFAULT NOW(),
    accrual NUMERIC NOT NULL DEFAULT 0,
    pending BOOLEAN NOT NULL DEFAULT FALSE
);