// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/max-marek-projects/loyalty-system/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

type Storage_Expecter struct {
	mock *mock.Mock
}

func (_m *Storage) EXPECT() *Storage_Expecter {
	return &Storage_Expecter{mock: &_m.Mock}
}

// AddOrder provides a mock function with given fields: ctx, userID, orderNumber
func (_m *Storage) AddOrder(ctx context.Context, userID int64, orderNumber string) error {
	ret := _m.Called(ctx, userID, orderNumber)

	if len(ret) == 0 {
		panic("no return value specified for AddOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, userID, orderNumber)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_AddOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddOrder'
type Storage_AddOrder_Call struct {
	*mock.Call
}

// AddOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - orderNumber string
func (_e *Storage_Expecter) AddOrder(ctx interface{}, userID interface{}, orderNumber interface{}) *Storage_AddOrder_Call {
	return &Storage_AddOrder_Call{Call: _e.mock.On("AddOrder", ctx, userID, orderNumber)}
}

func (_c *Storage_AddOrder_Call) Run(run func(ctx context.Context, userID int64, orderNumber string)) *Storage_AddOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *Storage_AddOrder_Call) Return(_a0 error) *Storage_AddOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_AddOrder_Call) RunAndReturn(run func(context.Context, int64, string) error) *Storage_AddOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CheckUser provides a mock function with given fields: ctx, username
func (_m *Storage) CheckUser(ctx context.Context, username string) (int64, string, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for CheckUser")
	}

	var r0 int64
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, string, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, username)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Storage_CheckUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckUser'
type Storage_CheckUser_Call struct {
	*mock.Call
}

// CheckUser is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *Storage_Expecter) CheckUser(ctx interface{}, username interface{}) *Storage_CheckUser_Call {
	return &Storage_CheckUser_Call{Call: _e.mock.On("CheckUser", ctx, username)}
}

func (_c *Storage_CheckUser_Call) Run(run func(ctx context.Context, username string)) *Storage_CheckUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Storage_CheckUser_Call) Return(_a0 int64, _a1 string, _a2 error) *Storage_CheckUser_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Storage_CheckUser_Call) RunAndReturn(run func(context.Context, string) (int64, string, error)) *Storage_CheckUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindAndClaimNewOrders provides a mock function with given fields: ctx
func (_m *Storage) FindAndClaimNewOrders(ctx context.Context) ([]models.OrderData, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAndClaimNewOrders")
	}

	var r0 []models.OrderData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.OrderData, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.OrderData); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.OrderData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_FindAndClaimNewOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAndClaimNewOrders'
type Storage_FindAndClaimNewOrders_Call struct {
	*mock.Call
}

// FindAndClaimNewOrders is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Storage_Expecter) FindAndClaimNewOrders(ctx interface{}) *Storage_FindAndClaimNewOrders_Call {
	return &Storage_FindAndClaimNewOrders_Call{Call: _e.mock.On("FindAndClaimNewOrders", ctx)}
}

func (_c *Storage_FindAndClaimNewOrders_Call) Run(run func(ctx context.Context)) *Storage_FindAndClaimNewOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Storage_FindAndClaimNewOrders_Call) Return(_a0 []models.OrderData, _a1 error) *Storage_FindAndClaimNewOrders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_FindAndClaimNewOrders_Call) RunAndReturn(run func(context.Context) ([]models.OrderData, error)) *Storage_FindAndClaimNewOrders_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllOrders provides a mock function with given fields: ctx, userID
func (_m *Storage) GetAllOrders(ctx context.Context, userID int64) ([]models.OrderData, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllOrders")
	}

	var r0 []models.OrderData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]models.OrderData, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []models.OrderData); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.OrderData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_GetAllOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllOrders'
type Storage_GetAllOrders_Call struct {
	*mock.Call
}

// GetAllOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *Storage_Expecter) GetAllOrders(ctx interface{}, userID interface{}) *Storage_GetAllOrders_Call {
	return &Storage_GetAllOrders_Call{Call: _e.mock.On("GetAllOrders", ctx, userID)}
}

func (_c *Storage_GetAllOrders_Call) Run(run func(ctx context.Context, userID int64)) *Storage_GetAllOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Storage_GetAllOrders_Call) Return(_a0 []models.OrderData, _a1 error) *Storage_GetAllOrders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_GetAllOrders_Call) RunAndReturn(run func(context.Context, int64) ([]models.OrderData, error)) *Storage_GetAllOrders_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAllProcessingAsNew provides a mock function with given fields: ctx
func (_m *Storage) MarkAllProcessingAsNew(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for MarkAllProcessingAsNew")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_MarkAllProcessingAsNew_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAllProcessingAsNew'
type Storage_MarkAllProcessingAsNew_Call struct {
	*mock.Call
}

// MarkAllProcessingAsNew is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Storage_Expecter) MarkAllProcessingAsNew(ctx interface{}) *Storage_MarkAllProcessingAsNew_Call {
	return &Storage_MarkAllProcessingAsNew_Call{Call: _e.mock.On("MarkAllProcessingAsNew", ctx)}
}

func (_c *Storage_MarkAllProcessingAsNew_Call) Run(run func(ctx context.Context)) *Storage_MarkAllProcessingAsNew_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Storage_MarkAllProcessingAsNew_Call) Return(_a0 error) *Storage_MarkAllProcessingAsNew_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_MarkAllProcessingAsNew_Call) RunAndReturn(run func(context.Context) error) *Storage_MarkAllProcessingAsNew_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterUser provides a mock function with given fields: ctx, userData
func (_m *Storage) RegisterUser(ctx context.Context, userData models.UserData) (int64, error) {
	ret := _m.Called(ctx, userData)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserData) (int64, error)); ok {
		return rf(ctx, userData)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UserData) int64); ok {
		r0 = rf(ctx, userData)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UserData) error); ok {
		r1 = rf(ctx, userData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_RegisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterUser'
type Storage_RegisterUser_Call struct {
	*mock.Call
}

// RegisterUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userData models.UserData
func (_e *Storage_Expecter) RegisterUser(ctx interface{}, userData interface{}) *Storage_RegisterUser_Call {
	return &Storage_RegisterUser_Call{Call: _e.mock.On("RegisterUser", ctx, userData)}
}

func (_c *Storage_RegisterUser_Call) Run(run func(ctx context.Context, userData models.UserData)) *Storage_RegisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.UserData))
	})
	return _c
}

func (_c *Storage_RegisterUser_Call) Return(_a0 int64, _a1 error) *Storage_RegisterUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_RegisterUser_Call) RunAndReturn(run func(context.Context, models.UserData) (int64, error)) *Storage_RegisterUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
