// Code generated by mockery v2.53.6. DO NOT EDIT.

package handlers

import (
	context "context"

	models "github.com/max-marek-projects/loyalty-system/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// AddOrder provides a mock function with given fields: ctx, userID, orderNumber
func (_m *Service) AddOrder(ctx context.Context, userID int64, orderNumber string) (bool, error) {
	ret := _m.Called(ctx, userID, orderNumber)

	if len(ret) == 0 {
		panic("no return value specified for AddOrder")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) (bool, error)); ok {
		return rf(ctx, userID, orderNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) bool); ok {
		r0 = rf(ctx, userID, orderNumber)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = rf(ctx, userID, orderNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_AddOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddOrder'
type Service_AddOrder_Call struct {
	*mock.Call
}

// AddOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - orderNumber string
func (_e *Service_Expecter) AddOrder(ctx interface{}, userID interface{}, orderNumber interface{}) *Service_AddOrder_Call {
	return &Service_AddOrder_Call{Call: _e.mock.On("AddOrder", ctx, userID, orderNumber)}
}

func (_c *Service_AddOrder_Call) Run(run func(ctx context.Context, userID int64, orderNumber string)) *Service_AddOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *Service_AddOrder_Call) Return(_a0 bool, _a1 error) *Service_AddOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_AddOrder_Call) RunAndReturn(run func(context.Context, int64, string) (bool, error)) *Service_AddOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllOrders provides a mock function with given fields: ctx, userID
func (_m *Service) GetAllOrders(ctx context.Context, userID int64) ([]models.OrderData, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllOrders")
	}

	var r0 []models.OrderData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]models.OrderData, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []models.OrderData); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.OrderData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetAllOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllOrders'
type Service_GetAllOrders_Call struct {
	*mock.Call
}

// GetAllOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *Service_Expecter) GetAllOrders(ctx interface{}, userID interface{}) *Service_GetAllOrders_Call {
	return &Service_GetAllOrders_Call{Call: _e.mock.On("GetAllOrders", ctx, userID)}
}

func (_c *Service_GetAllOrders_Call) Run(run func(ctx context.Context, userID int64)) *Service_GetAllOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Service_GetAllOrders_Call) Return(_a0 []models.OrderData, _a1 error) *Service_GetAllOrders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetAllOrders_Call) RunAndReturn(run func(context.Context, int64) ([]models.OrderData, error)) *Service_GetAllOrders_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllWithdrawals provides a mock function with given fields: ctx, userID
func (_m *Service) GetAllWithdrawals(ctx context.Context, userID int64) ([]models.WithdrawData, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllWithdrawals")
	}

	var r0 []models.WithdrawData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]models.WithdrawData, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []models.WithdrawData); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.WithdrawData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetAllWithdrawals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllWithdrawals'
type Service_GetAllWithdrawals_Call struct {
	*mock.Call
}

// GetAllWithdrawals is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *Service_Expecter) GetAllWithdrawals(ctx interface{}, userID interface{}) *Service_GetAllWithdrawals_Call {
	return &Service_GetAllWithdrawals_Call{Call: _e.mock.On("GetAllWithdrawals", ctx, userID)}
}

func (_c *Service_GetAllWithdrawals_Call) Run(run func(ctx context.Context, userID int64)) *Service_GetAllWithdrawals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Service_GetAllWithdrawals_Call) Return(_a0 []models.WithdrawData, _a1 error) *Service_GetAllWithdrawals_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetAllWithdrawals_Call) RunAndReturn(run func(context.Context, int64) ([]models.WithdrawData, error)) *Service_GetAllWithdrawals_Call {
	_c.Call.Return(run)
	return _c
}

// GetBalance provides a mock function with given fields: ctx, userID
func (_m *Service) GetBalance(ctx context.Context, userID int64) (*models.BalanceData, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 *models.BalanceData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.BalanceData, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.BalanceData); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.BalanceData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type Service_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *Service_Expecter) GetBalance(ctx interface{}, userID interface{}) *Service_GetBalance_Call {
	return &Service_GetBalance_Call{Call: _e.mock.On("GetBalance", ctx, userID)}
}

func (_c *Service_GetBalance_Call) Run(run func(ctx context.Context, userID int64)) *Service_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Service_GetBalance_Call) Return(_a0 *models.BalanceData, _a1 error) *Service_GetBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetBalance_Call) RunAndReturn(run func(context.Context, int64) (*models.BalanceData, error)) *Service_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// LoginUser provides a mock function with given fields: ctx, userData
func (_m *Service) LoginUser(ctx context.Context, userData models.RegisterRequest) (int64, error) {
	ret := _m.Called(ctx, userData)

	if len(ret) == 0 {
		panic("no return value specified for LoginUser")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.RegisterRequest) (int64, error)); ok {
		return rf(ctx, userData)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.RegisterRequest) int64); ok {
		r0 = rf(ctx, userData)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.RegisterRequest) error); ok {
		r1 = rf(ctx, userData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_LoginUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoginUser'
type Service_LoginUser_Call struct {
	*mock.Call
}

// LoginUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userData models.RegisterRequest
func (_e *Service_Expecter) LoginUser(ctx interface{}, userData interface{}) *Service_LoginUser_Call {
	return &Service_LoginUser_Call{Call: _e.mock.On("LoginUser", ctx, userData)}
}

func (_c *Service_LoginUser_Call) Run(run func(ctx context.Context, userData models.RegisterRequest)) *Service_LoginUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.RegisterRequest))
	})
	return _c
}

func (_c *Service_LoginUser_Call) Return(_a0 int64, _a1 error) *Service_LoginUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_LoginUser_Call) RunAndReturn(run func(context.Context, models.RegisterRequest) (int64, error)) *Service_LoginUser_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterUser provides a mock function with given fields: ctx, userData
func (_m *Service) RegisterUser(ctx context.Context, userData models.RegisterRequest) (int64, error) {
	ret := _m.Called(ctx, userData)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.RegisterRequest) (int64, error)); ok {
		return rf(ctx, userData)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.RegisterRequest) int64); ok {
		r0 = rf(ctx, userData)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.RegisterRequest) error); ok {
		r1 = rf(ctx, userData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_RegisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterUser'
type Service_RegisterUser_Call struct {
	*mock.Call
}

// RegisterUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userData models.RegisterRequest
func (_e *Service_Expecter) RegisterUser(ctx interface{}, userData interface{}) *Service_RegisterUser_Call {
	return &Service_RegisterUser_Call{Call: _e.mock.On("RegisterUser", ctx, userData)}
}

func (_c *Service_RegisterUser_Call) Run(run func(ctx context.Context, userData models.RegisterRequest)) *Service_RegisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.RegisterRequest))
	})
	return _c
}

func (_c *Service_RegisterUser_Call) Return(_a0 int64, _a1 error) *Service_RegisterUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_RegisterUser_Call) RunAndReturn(run func(context.Context, models.RegisterRequest) (int64, error)) *Service_RegisterUser_Call {
	_c.Call.Return(run)
	return _c
}

// StartOrderProcessor provides a mock function with given fields: ctx, maxParallelWorkers, pollInterval, mockExternalService
func (_m *Service) StartOrderProcessor(ctx context.Context, maxParallelWorkers int, pollInterval int, mockExternalService bool) {
	_m.Called(ctx, maxParallelWorkers, pollInterval, mockExternalService)
}

// Service_StartOrderProcessor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartOrderProcessor'
type Service_StartOrderProcessor_Call struct {
	*mock.Call
}

// StartOrderProcessor is a helper method to define mock.On call
//   - ctx context.Context
//   - maxParallelWorkers int
//   - pollInterval int
//   - mockExternalService bool
func (_e *Service_Expecter) StartOrderProcessor(ctx interface{}, maxParallelWorkers interface{}, pollInterval interface{}, mockExternalService interface{}) *Service_StartOrderProcessor_Call {
	return &Service_StartOrderProcessor_Call{Call: _e.mock.On("StartOrderProcessor", ctx, maxParallelWorkers, pollInterval, mockExternalService)}
}

func (_c *Service_StartOrderProcessor_Call) Run(run func(ctx context.Context, maxParallelWorkers int, pollInterval int, mockExternalService bool)) *Service_StartOrderProcessor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(bool))
	})
	return _c
}

func (_c *Service_StartOrderProcessor_Call) Return() *Service_StartOrderProcessor_Call {
	_c.Call.Return()
	return _c
}

func (_c *Service_StartOrderProcessor_Call) RunAndReturn(run func(context.Context, int, int, bool)) *Service_StartOrderProcessor_Call {
	_c.Run(run)
	return _c
}

// Withdraw provides a mock function with given fields: ctx, userID, orderNumber, sum
func (_m *Service) Withdraw(ctx context.Context, userID int64, orderNumber string, sum float64) error {
	ret := _m.Called(ctx, userID, orderNumber, sum)

	if len(ret) == 0 {
		panic("no return value specified for Withdraw")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, float64) error); ok {
		r0 = rf(ctx, userID, orderNumber, sum)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_Withdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Withdraw'
type Service_Withdraw_Call struct {
	*mock.Call
}

// Withdraw is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - orderNumber string
//   - sum float64
func (_e *Service_Expecter) Withdraw(ctx interface{}, userID interface{}, orderNumber interface{}, sum interface{}) *Service_Withdraw_Call {
	return &Service_Withdraw_Call{Call: _e.mock.On("Withdraw", ctx, userID, orderNumber, sum)}
}

func (_c *Service_Withdraw_Call) Run(run func(ctx context.Context, userID int64, orderNumber string, sum float64)) *Service_Withdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].(float64))
	})
	return _c
}

func (_c *Service_Withdraw_Call) Return(_a0 error) *Service_Withdraw_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_Withdraw_Call) RunAndReturn(run func(context.Context, int64, string, float64) error) *Service_Withdraw_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
